services:
  # Main Android Node
  android-research:
    build:
      context: .
      dockerfile: Dockerfile.research
    container_name: android-research-lab
    privileged: true
    volumes:
      - ./data:/data
      - ./modules:/flash_dir # Drop Shamiko.zip here
    ports:
      - "5555:5555" # ADB
    command:
      - androidboot.redroid_width=1080
      - androidboot.redroid_height=1920
      - androidboot.redroid_fps=3
      - androidboot.redroid_gpu_mode=host
      - androidboot.use_memfd=true
      - androidboot.use_redroid_overlayfs=true
    restart: unless-stopped

  # Visualizer
  #visual-ui:
  #  build: https://github.com/n1n3b1t/ws-scrcpy.git
  #  # image: n1n3b1t/ws-scrcpy
  #  container_name: android-research-ui
  #  ports:
  #    - "8000:8000"
  #  depends_on:
  #    - android-research


